wandb_version: 1

max_depth:
  desc: null
  value: 3
n_estimators:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.9.10
    cli_version: 0.14.2
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1682607951.688532
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.10
      5: 0.14.2
      8:
      - 1
      - 5
