wandb_version: 1

k:
  desc: null
  value: 9
_wandb:
  desc: null
  value:
    python_version: 3.9.10
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1682774888.403355
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 33
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 33
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.10
      5: 0.14.2
      8:
      - 1
      - 5
