wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.10
    cli_version: 0.14.2
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1681914184.7701
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.9.10
      5: 0.14.2
      8:
      - 1
      - 5
    viz:
      learning_curve:
        id: wandb/learning_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: learning_curve
